<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
    <Folder Include="Helpers\" />
    <Folder Include="Extensions\" />
    <Folder Include="Persistences\Context\" />
    <Folder Include="Persistences\Interfaces\" />
    <Folder Include="Persistences\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.4.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Movie.Domain\Movie.Domain.csproj" />
    <ProjectReference Include="..\Movie.Utilities\Movie.Utilities.csproj" />
  </ItemGroup>

</Project>
